### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by ashutoshtrack** [assemmohamedali/react-native-facerecognition#13]
- M unable to set your example code up and running
- Integrating library with react native had to done few fixes on configurations side

Even though i managed to get It up and Running,
It says "OpenCv manager not found. Trying to install OpenCv" 
- on yes redirects to playstore which says item not found.

its visibly seen throwing  error

com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'mounted' of a view managed by: FaceCamera
   at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:139)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)

**Comment by aboozaid** [comment]
You need to read the documentation again, You need to know your phone's CPU and then choose which jniLibs you need to download.
